### PR TITLE
Added username and password to reqired

### PR DESCRIPTION
**Pull request by ComlOnline**
Need to build as final check nothing broke.

### CODE REVIEW

**Comment by brain0** [comment]
Why would this be desired? librespot works just well in "discovery mode" without giving a username or password.

**Comment by ComlOnline** [comment]
From what I understood, and found in testing librespot needs a premium account signed into it for it to work. I may be wrong however so will check that this weekend, Thanks for making me check!

**Comment by ComlOnline** [comment]
@brain0 What version of librespot are you using?

**Comment by brain0** [comment]
Librespot signs itself in with your credentials as soon as you connect a spotify client to it. A premium account is still required of course, but there is no need to store the credentials on the librespot host. I am using it this way with the official Android and Linux Desktop spotify client.

I am running the latest git master of librespot.

**Comment by fossedihelm** [comment]
Agree with @brain0. Premium account is required to use "spotify connect", otherwise you cannot use this feature. You can set username and password to librespot if you want to have the device availaible in internet (not in the same network). In my honest opinion there're no reasons to require this information as mandatory.

**Comment by ComlOnline** [comment]
Thanks for clearing that up @brain0  and @fossedihelm I misunderstood how that aspect of it worked. I may add that to the readme to make it clearer.

**Pull request closed without merging**
